//// Generated by spider on 2020-04-08 00:15:05.672826

class Images {
  static const String arrowRight = 'assets/images/arrow_right.png';
  static const String statistics = 'assets/images/statistics.png';
  static const String settings = 'assets/images/settings.png';
  static const String arrowLeft = 'assets/images/arrow_left.png';
}
